### ISSUE TITLE
What command do you use to start the farmer

### ISSUE THREAD

**Issue by VercauterenK** [iwex/chiascripts#1]
Hi,

First off all thanks for the scripts ;-)
I have chia monitor running and i can see the harvesters files but the expected xch and earned xch and netspace etc doesn't show up. Can you give me the command on how to start the farmer with the wallet that is in it.

Thanks Kevin

**Comment by VercauterenK** [comment]
also if possible could you give the command to open the GUI automaticly now i installed it like an harvester but i start it as an farmer.

**Comment by iwex** [comment]
Hello! I work only with cli and don't have GUI, so I can't help you with it.
I have some main node with fully synced wallet and blockchain and I run there `chia start farmer`. On other machines, I have only harvesters `chia start harvester`. https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines
What is your infrastructure?

**Comment by VercauterenK** [comment]
Hi,

Thanks for the answer i changed my infrastructure.
Here is the image of the diagram that i made. 
https://www.mobilrent.be/infra.png
everything is finally running after 4 days of setup and hardware placing

Plotter 1 -> Plotter 6 =       CPU AMD 5900x
                                             2 x 2TB pcie 4 nvme
                                             1 x 1TB pcie 1 ssd
                                             64 GB ram
                                             1 x 10TB external HDD (ass buffer to archive to harvester)
                                             Using plotman with archival

Plotter 7 / Harvester 4  =    CPU AMD threadripper 3990x
                                             3 x 2TB pcie 4 nvme
                                             256 GB Ram
                                             9 x 1TB pcie 3 ssd (can be maxed to 4x5)
                                             13 x 10TB external HDD ( max is 13x7)
                                             using plotman

Harvesters                    =     CPU I5 processor
                                             32 GB RAM
                                             13 x 10TB external HDD ( max is 13x7)

Farmer                        =       CPU AMD 5900x
                                             64 GB ram

There are still 4 plotters and 2 harvester that are gonna be delivered this week. Will it be good to still use 1 farmer if i max out the HDD so 13x7 per harvester.

My farmer is running chia monitor and every harvester is slave chia monitor. Now i noticed when i open the chia monitor dash the average challenge go from 70 to 32 per 5 min.

All machines are using chia cli linux and i have 1 windows pc at home that is running my wallet to make transfers etc other pc are in my farming / magazin.

I am totally new to HDD mining but i am doiing gpu for 5 years and have around 500 rigs. Since gpu's are hard to get and i just bought my 3th warehouse i filling it up with HDD mining (it takes so few electrical power and place that i can make it huge).
There are 500 HDD on my way gonna be delivered in parts.

What do you think about the setup?

**Comment by VercauterenK** [comment]
> also if possible could you give the command to open the GUI automaticly now i installed it like an harvester but i start it as an farmer.

I also needed to put the farmer ip as harvester ip adres in prometheus conf
That fixed the problem

**Comment by VercauterenK** [comment]
> Hi,
> 
> First off all thanks for the scripts ;-)
> I have chia monitor running and i can see the harvesters files but the expected xch and earned xch and netspace etc doesn't show up. Can you give me the command on how to start the farmer with the wallet that is in it.
> 
> Thanks Kevin

I also needed to put the farmer ip as harvester ip adres in prometheus conf
That fixed the problem

**Comment by iwex** [comment]
@VercauterenK so everything is ok now?
You have a good setup :)

**Comment by VercauterenK** [comment]
Yeah only have 1 problem, the plotters makes the files to fast and they can't send them in time to harvesters. Any idea how i can let send 1 plotter to multiple harvester?

**Comment by iwex** [comment]
Are you talking about plotman archive function?

**Comment by VercauterenK** [comment]
Yes

**Comment by iwex** [comment]
I don't know. I manually move my plots)
